/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s292_1
#  OS:                Linux x86_64(Host ID saturn.ece.iit.edu)
#  Generated on:      Sat Nov 17 14:17:41 2012
#  Design:            adder7_8
#  Command:           saveNetlist -excludeLeafCell final.v
###############################################################
*/
module adder7_8 (
	s, 
	co, 
	a, 
	b, 
	c, 
	d, 
	e, 
	f, 
	g, 
	h, 
	ci);
   output [6:0] s;
   output co;
   input [6:0] a;
   input [6:0] b;
   input [6:0] c;
   input [6:0] d;
   input [6:0] e;
   input [6:0] f;
   input [6:0] g;
   input [6:0] h;
   input ci;

   // Internal wires
   wire co1;
   wire co2;
   wire co3;
   wire co4;
   wire co5;
   wire co6;
   wire \a0/c6 ;
   wire \a0/c5 ;
   wire \a0/c4 ;
   wire \a0/c3 ;
   wire \a0/c2 ;
   wire \a0/c1 ;
   wire \a0/a0/n3 ;
   wire \a0/a0/n2 ;
   wire \a0/a0/n1 ;
   wire \a6/c6 ;
   wire \a6/c5 ;
   wire \a6/c4 ;
   wire \a6/c3 ;
   wire \a6/c2 ;
   wire \a6/c1 ;
   wire \a5/c6 ;
   wire \a5/c5 ;
   wire \a5/c4 ;
   wire \a5/c3 ;
   wire \a5/c2 ;
   wire \a5/c1 ;
   wire \a4/c6 ;
   wire \a4/c5 ;
   wire \a4/c4 ;
   wire \a4/c3 ;
   wire \a4/c2 ;
   wire \a4/c1 ;
   wire \a3/c6 ;
   wire \a3/c5 ;
   wire \a3/c4 ;
   wire \a3/c3 ;
   wire \a3/c2 ;
   wire \a3/c1 ;
   wire \a2/c6 ;
   wire \a2/c5 ;
   wire \a2/c4 ;
   wire \a2/c3 ;
   wire \a2/c2 ;
   wire \a2/c1 ;
   wire \a1/c6 ;
   wire \a1/c5 ;
   wire \a1/c4 ;
   wire \a1/c3 ;
   wire \a1/c2 ;
   wire \a1/c1 ;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire [6:0] s1;
   wire [6:0] s2;
   wire [6:0] s3;
   wire [6:0] s4;
   wire [6:0] s5;
   wire [6:0] s6;

   XNOR2X1 \a0/a0/U5  (.Y(\a0/a0/n2 ), 
	.B(b[0]), 
	.A(a[0]));
   OAI21X1 \a0/a0/U3  (.Y(\a0/c1 ), 
	.C(n17), 
	.B(\a0/a0/n1 ), 
	.A(\a0/a0/n2 ));
   XOR2X1 \a0/a0/U2  (.Y(s1[0]), 
	.B(\a0/a0/n2 ), 
	.A(\a0/a0/n1 ));
   XNOR2X1 \a6/a6/U5  (.Y(n192), 
	.B(s6[6]), 
	.A(h[6]));
   OAI21X1 \a6/a6/U3  (.Y(co), 
	.C(n18), 
	.B(n191), 
	.A(n192));
   XOR2X1 \a6/a6/U2  (.Y(s[6]), 
	.B(n192), 
	.A(n191));
   XNOR2X1 \a6/a5/U5  (.Y(n189), 
	.B(s6[5]), 
	.A(h[5]));
   OAI21X1 \a6/a5/U3  (.Y(\a6/c6 ), 
	.C(n34), 
	.B(n188), 
	.A(n189));
   XOR2X1 \a6/a5/U2  (.Y(s[5]), 
	.B(n189), 
	.A(n188));
   XNOR2X1 \a6/a4/U5  (.Y(n186), 
	.B(s6[4]), 
	.A(h[4]));
   OAI21X1 \a6/a4/U3  (.Y(\a6/c5 ), 
	.C(n2), 
	.B(n185), 
	.A(n186));
   XOR2X1 \a6/a4/U2  (.Y(s[4]), 
	.B(n186), 
	.A(n185));
   XNOR2X1 \a6/a3/U5  (.Y(n183), 
	.B(s6[3]), 
	.A(h[3]));
   OAI21X1 \a6/a3/U3  (.Y(\a6/c4 ), 
	.C(n19), 
	.B(n182), 
	.A(n183));
   XOR2X1 \a6/a3/U2  (.Y(s[3]), 
	.B(n183), 
	.A(n182));
   XNOR2X1 \a6/a2/U5  (.Y(n180), 
	.B(s6[2]), 
	.A(h[2]));
   OAI21X1 \a6/a2/U3  (.Y(\a6/c3 ), 
	.C(n35), 
	.B(n179), 
	.A(n180));
   XOR2X1 \a6/a2/U2  (.Y(s[2]), 
	.B(n180), 
	.A(n179));
   XNOR2X1 \a6/a1/U5  (.Y(n177), 
	.B(s6[1]), 
	.A(h[1]));
   OAI21X1 \a6/a1/U3  (.Y(\a6/c2 ), 
	.C(n3), 
	.B(n176), 
	.A(n177));
   XOR2X1 \a6/a1/U2  (.Y(s[1]), 
	.B(n177), 
	.A(n176));
   XNOR2X1 \a6/a0/U5  (.Y(n174), 
	.B(s6[0]), 
	.A(h[0]));
   OAI21X1 \a6/a0/U3  (.Y(\a6/c1 ), 
	.C(n20), 
	.B(n173), 
	.A(n174));
   XOR2X1 \a6/a0/U2  (.Y(s[0]), 
	.B(n174), 
	.A(n173));
   XNOR2X1 \a5/a6/U5  (.Y(n171), 
	.B(s5[6]), 
	.A(g[6]));
   OAI21X1 \a5/a6/U3  (.Y(co6), 
	.C(n36), 
	.B(n170), 
	.A(n171));
   XOR2X1 \a5/a6/U2  (.Y(s6[6]), 
	.B(n171), 
	.A(n170));
   XNOR2X1 \a5/a5/U5  (.Y(n168), 
	.B(s5[5]), 
	.A(g[5]));
   OAI21X1 \a5/a5/U3  (.Y(\a5/c6 ), 
	.C(n4), 
	.B(n167), 
	.A(n168));
   XOR2X1 \a5/a5/U2  (.Y(s6[5]), 
	.B(n168), 
	.A(n167));
   XNOR2X1 \a5/a4/U5  (.Y(n165), 
	.B(s5[4]), 
	.A(g[4]));
   OAI21X1 \a5/a4/U3  (.Y(\a5/c5 ), 
	.C(n21), 
	.B(n164), 
	.A(n165));
   XOR2X1 \a5/a4/U2  (.Y(s6[4]), 
	.B(n165), 
	.A(n164));
   XNOR2X1 \a5/a3/U5  (.Y(n162), 
	.B(s5[3]), 
	.A(g[3]));
   OAI21X1 \a5/a3/U3  (.Y(\a5/c4 ), 
	.C(n37), 
	.B(n161), 
	.A(n162));
   XOR2X1 \a5/a3/U2  (.Y(s6[3]), 
	.B(n162), 
	.A(n161));
   XNOR2X1 \a5/a2/U5  (.Y(n159), 
	.B(s5[2]), 
	.A(g[2]));
   OAI21X1 \a5/a2/U3  (.Y(\a5/c3 ), 
	.C(n5), 
	.B(n158), 
	.A(n159));
   XOR2X1 \a5/a2/U2  (.Y(s6[2]), 
	.B(n159), 
	.A(n158));
   XNOR2X1 \a5/a1/U5  (.Y(n156), 
	.B(s5[1]), 
	.A(g[1]));
   OAI21X1 \a5/a1/U3  (.Y(\a5/c2 ), 
	.C(n22), 
	.B(n155), 
	.A(n156));
   XOR2X1 \a5/a1/U2  (.Y(s6[1]), 
	.B(n156), 
	.A(n155));
   XNOR2X1 \a5/a0/U5  (.Y(n153), 
	.B(s5[0]), 
	.A(g[0]));
   OAI21X1 \a5/a0/U3  (.Y(\a5/c1 ), 
	.C(n38), 
	.B(n152), 
	.A(n153));
   XOR2X1 \a5/a0/U2  (.Y(s6[0]), 
	.B(n153), 
	.A(n152));
   XNOR2X1 \a4/a6/U5  (.Y(n150), 
	.B(s4[6]), 
	.A(f[6]));
   OAI21X1 \a4/a6/U3  (.Y(co5), 
	.C(n6), 
	.B(n149), 
	.A(n150));
   XOR2X1 \a4/a6/U2  (.Y(s5[6]), 
	.B(n150), 
	.A(n149));
   XNOR2X1 \a4/a5/U5  (.Y(n147), 
	.B(s4[5]), 
	.A(f[5]));
   OAI21X1 \a4/a5/U3  (.Y(\a4/c6 ), 
	.C(n23), 
	.B(n146), 
	.A(n147));
   XOR2X1 \a4/a5/U2  (.Y(s5[5]), 
	.B(n147), 
	.A(n146));
   XNOR2X1 \a4/a4/U5  (.Y(n144), 
	.B(s4[4]), 
	.A(f[4]));
   OAI21X1 \a4/a4/U3  (.Y(\a4/c5 ), 
	.C(n39), 
	.B(n143), 
	.A(n144));
   XOR2X1 \a4/a4/U2  (.Y(s5[4]), 
	.B(n144), 
	.A(n143));
   XNOR2X1 \a4/a3/U5  (.Y(n141), 
	.B(s4[3]), 
	.A(f[3]));
   OAI21X1 \a4/a3/U3  (.Y(\a4/c4 ), 
	.C(n7), 
	.B(n140), 
	.A(n141));
   XOR2X1 \a4/a3/U2  (.Y(s5[3]), 
	.B(n141), 
	.A(n140));
   XNOR2X1 \a4/a2/U5  (.Y(n138), 
	.B(s4[2]), 
	.A(f[2]));
   OAI21X1 \a4/a2/U3  (.Y(\a4/c3 ), 
	.C(n24), 
	.B(n137), 
	.A(n138));
   XOR2X1 \a4/a2/U2  (.Y(s5[2]), 
	.B(n138), 
	.A(n137));
   XNOR2X1 \a4/a1/U5  (.Y(n135), 
	.B(s4[1]), 
	.A(f[1]));
   OAI21X1 \a4/a1/U3  (.Y(\a4/c2 ), 
	.C(n40), 
	.B(n134), 
	.A(n135));
   XOR2X1 \a4/a1/U2  (.Y(s5[1]), 
	.B(n135), 
	.A(n134));
   XNOR2X1 \a4/a0/U5  (.Y(n132), 
	.B(s4[0]), 
	.A(f[0]));
   OAI21X1 \a4/a0/U3  (.Y(\a4/c1 ), 
	.C(n8), 
	.B(n131), 
	.A(n132));
   XOR2X1 \a4/a0/U2  (.Y(s5[0]), 
	.B(n132), 
	.A(n131));
   XNOR2X1 \a3/a6/U5  (.Y(n129), 
	.B(s3[6]), 
	.A(e[6]));
   OAI21X1 \a3/a6/U3  (.Y(co4), 
	.C(n25), 
	.B(n128), 
	.A(n129));
   XOR2X1 \a3/a6/U2  (.Y(s4[6]), 
	.B(n129), 
	.A(n128));
   XNOR2X1 \a3/a5/U5  (.Y(n126), 
	.B(s3[5]), 
	.A(e[5]));
   OAI21X1 \a3/a5/U3  (.Y(\a3/c6 ), 
	.C(n41), 
	.B(n125), 
	.A(n126));
   XOR2X1 \a3/a5/U2  (.Y(s4[5]), 
	.B(n126), 
	.A(n125));
   XNOR2X1 \a3/a4/U5  (.Y(n123), 
	.B(s3[4]), 
	.A(e[4]));
   OAI21X1 \a3/a4/U3  (.Y(\a3/c5 ), 
	.C(n9), 
	.B(n122), 
	.A(n123));
   XOR2X1 \a3/a4/U2  (.Y(s4[4]), 
	.B(n123), 
	.A(n122));
   XNOR2X1 \a3/a3/U5  (.Y(n120), 
	.B(s3[3]), 
	.A(e[3]));
   OAI21X1 \a3/a3/U3  (.Y(\a3/c4 ), 
	.C(n26), 
	.B(n119), 
	.A(n120));
   XOR2X1 \a3/a3/U2  (.Y(s4[3]), 
	.B(n120), 
	.A(n119));
   XNOR2X1 \a3/a2/U5  (.Y(n117), 
	.B(s3[2]), 
	.A(e[2]));
   OAI21X1 \a3/a2/U3  (.Y(\a3/c3 ), 
	.C(n42), 
	.B(n116), 
	.A(n117));
   XOR2X1 \a3/a2/U2  (.Y(s4[2]), 
	.B(n117), 
	.A(n116));
   XNOR2X1 \a3/a1/U5  (.Y(n114), 
	.B(s3[1]), 
	.A(e[1]));
   OAI21X1 \a3/a1/U3  (.Y(\a3/c2 ), 
	.C(n10), 
	.B(n113), 
	.A(n114));
   XOR2X1 \a3/a1/U2  (.Y(s4[1]), 
	.B(n114), 
	.A(n113));
   XNOR2X1 \a3/a0/U5  (.Y(n111), 
	.B(s3[0]), 
	.A(e[0]));
   OAI21X1 \a3/a0/U3  (.Y(\a3/c1 ), 
	.C(n27), 
	.B(n110), 
	.A(n111));
   XOR2X1 \a3/a0/U2  (.Y(s4[0]), 
	.B(n111), 
	.A(n110));
   XNOR2X1 \a2/a6/U5  (.Y(n108), 
	.B(s2[6]), 
	.A(d[6]));
   OAI21X1 \a2/a6/U3  (.Y(co3), 
	.C(n43), 
	.B(n107), 
	.A(n108));
   XOR2X1 \a2/a6/U2  (.Y(s3[6]), 
	.B(n108), 
	.A(n107));
   XNOR2X1 \a2/a5/U5  (.Y(n105), 
	.B(s2[5]), 
	.A(d[5]));
   OAI21X1 \a2/a5/U3  (.Y(\a2/c6 ), 
	.C(n11), 
	.B(n104), 
	.A(n105));
   XOR2X1 \a2/a5/U2  (.Y(s3[5]), 
	.B(n105), 
	.A(n104));
   XNOR2X1 \a2/a4/U5  (.Y(n102), 
	.B(s2[4]), 
	.A(d[4]));
   OAI21X1 \a2/a4/U3  (.Y(\a2/c5 ), 
	.C(n28), 
	.B(n101), 
	.A(n102));
   XOR2X1 \a2/a4/U2  (.Y(s3[4]), 
	.B(n102), 
	.A(n101));
   XNOR2X1 \a2/a3/U5  (.Y(n99), 
	.B(s2[3]), 
	.A(d[3]));
   OAI21X1 \a2/a3/U3  (.Y(\a2/c4 ), 
	.C(n44), 
	.B(n98), 
	.A(n99));
   XOR2X1 \a2/a3/U2  (.Y(s3[3]), 
	.B(n99), 
	.A(n98));
   XNOR2X1 \a2/a2/U5  (.Y(n96), 
	.B(s2[2]), 
	.A(d[2]));
   OAI21X1 \a2/a2/U3  (.Y(\a2/c3 ), 
	.C(n12), 
	.B(n95), 
	.A(n96));
   XOR2X1 \a2/a2/U2  (.Y(s3[2]), 
	.B(n96), 
	.A(n95));
   XNOR2X1 \a2/a1/U5  (.Y(n93), 
	.B(s2[1]), 
	.A(d[1]));
   OAI21X1 \a2/a1/U3  (.Y(\a2/c2 ), 
	.C(n29), 
	.B(n92), 
	.A(n93));
   XOR2X1 \a2/a1/U2  (.Y(s3[1]), 
	.B(n93), 
	.A(n92));
   XNOR2X1 \a2/a0/U5  (.Y(n90), 
	.B(s2[0]), 
	.A(d[0]));
   OAI21X1 \a2/a0/U3  (.Y(\a2/c1 ), 
	.C(n45), 
	.B(n89), 
	.A(n90));
   XOR2X1 \a2/a0/U2  (.Y(s3[0]), 
	.B(n90), 
	.A(n89));
   XNOR2X1 \a1/a6/U5  (.Y(n87), 
	.B(s1[6]), 
	.A(c[6]));
   OAI21X1 \a1/a6/U3  (.Y(co2), 
	.C(n13), 
	.B(n86), 
	.A(n87));
   XOR2X1 \a1/a6/U2  (.Y(s2[6]), 
	.B(n87), 
	.A(n86));
   XNOR2X1 \a1/a5/U5  (.Y(n84), 
	.B(s1[5]), 
	.A(c[5]));
   OAI21X1 \a1/a5/U3  (.Y(\a1/c6 ), 
	.C(n30), 
	.B(n83), 
	.A(n84));
   XOR2X1 \a1/a5/U2  (.Y(s2[5]), 
	.B(n84), 
	.A(n83));
   XNOR2X1 \a1/a4/U5  (.Y(n81), 
	.B(s1[4]), 
	.A(c[4]));
   OAI21X1 \a1/a4/U3  (.Y(\a1/c5 ), 
	.C(n46), 
	.B(n80), 
	.A(n81));
   XOR2X1 \a1/a4/U2  (.Y(s2[4]), 
	.B(n81), 
	.A(n80));
   XNOR2X1 \a1/a3/U5  (.Y(n78), 
	.B(s1[3]), 
	.A(c[3]));
   OAI21X1 \a1/a3/U3  (.Y(\a1/c4 ), 
	.C(n14), 
	.B(n77), 
	.A(n78));
   XOR2X1 \a1/a3/U2  (.Y(s2[3]), 
	.B(n78), 
	.A(n77));
   XNOR2X1 \a1/a2/U5  (.Y(n75), 
	.B(s1[2]), 
	.A(c[2]));
   OAI21X1 \a1/a2/U3  (.Y(\a1/c3 ), 
	.C(n31), 
	.B(n74), 
	.A(n75));
   XOR2X1 \a1/a2/U2  (.Y(s2[2]), 
	.B(n75), 
	.A(n74));
   XNOR2X1 \a1/a1/U5  (.Y(n72), 
	.B(s1[1]), 
	.A(c[1]));
   OAI21X1 \a1/a1/U3  (.Y(\a1/c2 ), 
	.C(n47), 
	.B(n71), 
	.A(n72));
   XOR2X1 \a1/a1/U2  (.Y(s2[1]), 
	.B(n72), 
	.A(n71));
   XNOR2X1 \a1/a0/U5  (.Y(n69), 
	.B(s1[0]), 
	.A(c[0]));
   OAI21X1 \a1/a0/U3  (.Y(\a1/c1 ), 
	.C(n15), 
	.B(n68), 
	.A(n69));
   XOR2X1 \a1/a0/U2  (.Y(s2[0]), 
	.B(n69), 
	.A(n68));
   XNOR2X1 \a0/a6/U5  (.Y(n66), 
	.B(b[6]), 
	.A(a[6]));
   OAI21X1 \a0/a6/U3  (.Y(co1), 
	.C(n32), 
	.B(n65), 
	.A(n66));
   XOR2X1 \a0/a6/U2  (.Y(s1[6]), 
	.B(n66), 
	.A(n65));
   XNOR2X1 \a0/a5/U5  (.Y(n63), 
	.B(b[5]), 
	.A(a[5]));
   OAI21X1 \a0/a5/U3  (.Y(\a0/c6 ), 
	.C(n48), 
	.B(n62), 
	.A(n63));
   XOR2X1 \a0/a5/U2  (.Y(s1[5]), 
	.B(n63), 
	.A(n62));
   XNOR2X1 \a0/a4/U5  (.Y(n60), 
	.B(b[4]), 
	.A(a[4]));
   OAI21X1 \a0/a4/U3  (.Y(\a0/c5 ), 
	.C(n16), 
	.B(n59), 
	.A(n60));
   XOR2X1 \a0/a4/U2  (.Y(s1[4]), 
	.B(n60), 
	.A(n59));
   XNOR2X1 \a0/a3/U5  (.Y(n57), 
	.B(b[3]), 
	.A(a[3]));
   OAI21X1 \a0/a3/U3  (.Y(\a0/c4 ), 
	.C(n33), 
	.B(n56), 
	.A(n57));
   XOR2X1 \a0/a3/U2  (.Y(s1[3]), 
	.B(n57), 
	.A(n56));
   XNOR2X1 \a0/a2/U5  (.Y(n54), 
	.B(b[2]), 
	.A(a[2]));
   OAI21X1 \a0/a2/U3  (.Y(\a0/c3 ), 
	.C(n49), 
	.B(n53), 
	.A(n54));
   XOR2X1 \a0/a2/U2  (.Y(s1[2]), 
	.B(n54), 
	.A(n53));
   XNOR2X1 \a0/a1/U5  (.Y(n51), 
	.B(b[1]), 
	.A(a[1]));
   OAI21X1 \a0/a1/U3  (.Y(\a0/c2 ), 
	.C(n1), 
	.B(n50), 
	.A(n51));
   XOR2X1 \a0/a1/U2  (.Y(s1[1]), 
	.B(n51), 
	.A(n50));
   AND2X1 U1 (.Y(n52), 
	.B(b[1]), 
	.A(a[1]));
   INVX1 U2 (.Y(n1), 
	.A(n52));
   AND2X1 U3 (.Y(n187), 
	.B(s6[4]), 
	.A(h[4]));
   INVX1 U4 (.Y(n2), 
	.A(n187));
   AND2X1 U5 (.Y(n178), 
	.B(s6[1]), 
	.A(h[1]));
   INVX1 U6 (.Y(n3), 
	.A(n178));
   AND2X1 U7 (.Y(n169), 
	.B(s5[5]), 
	.A(g[5]));
   INVX1 U8 (.Y(n4), 
	.A(n169));
   AND2X1 U9 (.Y(n160), 
	.B(s5[2]), 
	.A(g[2]));
   INVX1 U10 (.Y(n5), 
	.A(n160));
   AND2X1 U11 (.Y(n151), 
	.B(s4[6]), 
	.A(f[6]));
   INVX1 U12 (.Y(n6), 
	.A(n151));
   AND2X1 U13 (.Y(n142), 
	.B(s4[3]), 
	.A(f[3]));
   INVX1 U14 (.Y(n7), 
	.A(n142));
   AND2X1 U15 (.Y(n133), 
	.B(s4[0]), 
	.A(f[0]));
   INVX1 U16 (.Y(n8), 
	.A(n133));
   AND2X1 U17 (.Y(n124), 
	.B(s3[4]), 
	.A(e[4]));
   INVX1 U18 (.Y(n9), 
	.A(n124));
   AND2X1 U19 (.Y(n115), 
	.B(s3[1]), 
	.A(e[1]));
   INVX1 U20 (.Y(n10), 
	.A(n115));
   AND2X1 U21 (.Y(n106), 
	.B(s2[5]), 
	.A(d[5]));
   INVX1 U22 (.Y(n11), 
	.A(n106));
   AND2X1 U23 (.Y(n97), 
	.B(s2[2]), 
	.A(d[2]));
   INVX1 U24 (.Y(n12), 
	.A(n97));
   AND2X1 U25 (.Y(n88), 
	.B(s1[6]), 
	.A(c[6]));
   INVX1 U26 (.Y(n13), 
	.A(n88));
   AND2X1 U27 (.Y(n79), 
	.B(s1[3]), 
	.A(c[3]));
   INVX1 U28 (.Y(n14), 
	.A(n79));
   AND2X1 U29 (.Y(n70), 
	.B(s1[0]), 
	.A(c[0]));
   INVX1 U30 (.Y(n15), 
	.A(n70));
   AND2X1 U31 (.Y(n61), 
	.B(b[4]), 
	.A(a[4]));
   INVX1 U32 (.Y(n16), 
	.A(n61));
   AND2X1 U33 (.Y(\a0/a0/n3 ), 
	.B(b[0]), 
	.A(a[0]));
   INVX1 U34 (.Y(n17), 
	.A(\a0/a0/n3 ));
   AND2X1 U35 (.Y(n193), 
	.B(s6[6]), 
	.A(h[6]));
   INVX1 U36 (.Y(n18), 
	.A(n193));
   AND2X1 U37 (.Y(n184), 
	.B(s6[3]), 
	.A(h[3]));
   INVX1 U38 (.Y(n19), 
	.A(n184));
   AND2X1 U39 (.Y(n175), 
	.B(s6[0]), 
	.A(h[0]));
   INVX1 U40 (.Y(n20), 
	.A(n175));
   AND2X1 U41 (.Y(n166), 
	.B(s5[4]), 
	.A(g[4]));
   INVX1 U42 (.Y(n21), 
	.A(n166));
   AND2X1 U43 (.Y(n157), 
	.B(s5[1]), 
	.A(g[1]));
   INVX1 U44 (.Y(n22), 
	.A(n157));
   AND2X1 U45 (.Y(n148), 
	.B(s4[5]), 
	.A(f[5]));
   INVX1 U46 (.Y(n23), 
	.A(n148));
   AND2X1 U47 (.Y(n139), 
	.B(s4[2]), 
	.A(f[2]));
   INVX1 U48 (.Y(n24), 
	.A(n139));
   AND2X1 U49 (.Y(n130), 
	.B(s3[6]), 
	.A(e[6]));
   INVX1 U50 (.Y(n25), 
	.A(n130));
   AND2X1 U51 (.Y(n121), 
	.B(s3[3]), 
	.A(e[3]));
   INVX1 U52 (.Y(n26), 
	.A(n121));
   AND2X1 U53 (.Y(n112), 
	.B(s3[0]), 
	.A(e[0]));
   INVX1 U54 (.Y(n27), 
	.A(n112));
   AND2X1 U55 (.Y(n103), 
	.B(s2[4]), 
	.A(d[4]));
   INVX1 U56 (.Y(n28), 
	.A(n103));
   AND2X1 U57 (.Y(n94), 
	.B(s2[1]), 
	.A(d[1]));
   INVX1 U58 (.Y(n29), 
	.A(n94));
   AND2X1 U59 (.Y(n85), 
	.B(s1[5]), 
	.A(c[5]));
   INVX1 U60 (.Y(n30), 
	.A(n85));
   AND2X1 U61 (.Y(n76), 
	.B(s1[2]), 
	.A(c[2]));
   INVX1 U62 (.Y(n31), 
	.A(n76));
   AND2X1 U63 (.Y(n67), 
	.B(b[6]), 
	.A(a[6]));
   INVX1 U64 (.Y(n32), 
	.A(n67));
   AND2X1 U65 (.Y(n58), 
	.B(b[3]), 
	.A(a[3]));
   INVX1 U66 (.Y(n33), 
	.A(n58));
   AND2X1 U67 (.Y(n190), 
	.B(s6[5]), 
	.A(h[5]));
   INVX1 U68 (.Y(n34), 
	.A(n190));
   AND2X1 U69 (.Y(n181), 
	.B(s6[2]), 
	.A(h[2]));
   INVX1 U70 (.Y(n35), 
	.A(n181));
   AND2X1 U71 (.Y(n172), 
	.B(s5[6]), 
	.A(g[6]));
   INVX1 U72 (.Y(n36), 
	.A(n172));
   AND2X1 U73 (.Y(n163), 
	.B(s5[3]), 
	.A(g[3]));
   INVX1 U74 (.Y(n37), 
	.A(n163));
   AND2X1 U75 (.Y(n154), 
	.B(s5[0]), 
	.A(g[0]));
   INVX1 U76 (.Y(n38), 
	.A(n154));
   AND2X1 U77 (.Y(n145), 
	.B(s4[4]), 
	.A(f[4]));
   INVX1 U78 (.Y(n39), 
	.A(n145));
   AND2X1 U79 (.Y(n136), 
	.B(s4[1]), 
	.A(f[1]));
   INVX1 U80 (.Y(n40), 
	.A(n136));
   AND2X1 U81 (.Y(n127), 
	.B(s3[5]), 
	.A(e[5]));
   INVX1 U82 (.Y(n41), 
	.A(n127));
   AND2X1 U83 (.Y(n118), 
	.B(s3[2]), 
	.A(e[2]));
   INVX1 U84 (.Y(n42), 
	.A(n118));
   AND2X1 U85 (.Y(n109), 
	.B(s2[6]), 
	.A(d[6]));
   INVX1 U86 (.Y(n43), 
	.A(n109));
   AND2X1 U87 (.Y(n100), 
	.B(s2[3]), 
	.A(d[3]));
   INVX1 U88 (.Y(n44), 
	.A(n100));
   AND2X1 U89 (.Y(n91), 
	.B(s2[0]), 
	.A(d[0]));
   INVX1 U90 (.Y(n45), 
	.A(n91));
   AND2X1 U91 (.Y(n82), 
	.B(s1[4]), 
	.A(c[4]));
   INVX1 U92 (.Y(n46), 
	.A(n82));
   AND2X1 U93 (.Y(n73), 
	.B(s1[1]), 
	.A(c[1]));
   INVX1 U94 (.Y(n47), 
	.A(n73));
   AND2X1 U95 (.Y(n64), 
	.B(b[5]), 
	.A(a[5]));
   INVX1 U96 (.Y(n48), 
	.A(n64));
   AND2X1 U97 (.Y(n55), 
	.B(b[2]), 
	.A(a[2]));
   INVX1 U98 (.Y(n49), 
	.A(n55));
   INVX2 U99 (.Y(n53), 
	.A(\a0/c2 ));
   INVX1 U100 (.Y(n113), 
	.A(\a3/c1 ));
   INVX1 U101 (.Y(n116), 
	.A(\a3/c2 ));
   INVX1 U102 (.Y(n119), 
	.A(\a3/c3 ));
   INVX1 U103 (.Y(n122), 
	.A(\a3/c4 ));
   INVX1 U104 (.Y(n125), 
	.A(\a3/c5 ));
   INVX1 U105 (.Y(n50), 
	.A(\a0/c1 ));
   INVX1 U106 (.Y(n56), 
	.A(\a0/c3 ));
   INVX1 U107 (.Y(n59), 
	.A(\a0/c4 ));
   INVX1 U108 (.Y(n62), 
	.A(\a0/c5 ));
   INVX1 U109 (.Y(n65), 
	.A(\a0/c6 ));
   INVX1 U110 (.Y(n68), 
	.A(co1));
   INVX1 U111 (.Y(n71), 
	.A(\a1/c1 ));
   INVX1 U112 (.Y(n74), 
	.A(\a1/c2 ));
   INVX1 U113 (.Y(n77), 
	.A(\a1/c3 ));
   INVX1 U114 (.Y(n80), 
	.A(\a1/c4 ));
   INVX1 U115 (.Y(n83), 
	.A(\a1/c5 ));
   INVX1 U116 (.Y(n86), 
	.A(\a1/c6 ));
   INVX1 U117 (.Y(n89), 
	.A(co2));
   INVX1 U118 (.Y(n92), 
	.A(\a2/c1 ));
   INVX1 U119 (.Y(n95), 
	.A(\a2/c2 ));
   INVX1 U120 (.Y(n98), 
	.A(\a2/c3 ));
   INVX1 U121 (.Y(n101), 
	.A(\a2/c4 ));
   INVX1 U122 (.Y(n104), 
	.A(\a2/c5 ));
   INVX1 U123 (.Y(n107), 
	.A(\a2/c6 ));
   INVX1 U124 (.Y(n110), 
	.A(co3));
   INVX1 U125 (.Y(n128), 
	.A(\a3/c6 ));
   INVX1 U126 (.Y(n131), 
	.A(co4));
   INVX1 U127 (.Y(n134), 
	.A(\a4/c1 ));
   INVX1 U128 (.Y(n137), 
	.A(\a4/c2 ));
   INVX1 U129 (.Y(n140), 
	.A(\a4/c3 ));
   INVX1 U130 (.Y(n143), 
	.A(\a4/c4 ));
   INVX1 U131 (.Y(n146), 
	.A(\a4/c5 ));
   INVX1 U132 (.Y(n149), 
	.A(\a4/c6 ));
   INVX1 U133 (.Y(n152), 
	.A(co5));
   INVX1 U134 (.Y(n155), 
	.A(\a5/c1 ));
   INVX1 U135 (.Y(n158), 
	.A(\a5/c2 ));
   INVX1 U136 (.Y(n161), 
	.A(\a5/c3 ));
   INVX1 U137 (.Y(n164), 
	.A(\a5/c4 ));
   INVX1 U138 (.Y(n167), 
	.A(\a5/c5 ));
   INVX1 U139 (.Y(n170), 
	.A(\a5/c6 ));
   INVX1 U140 (.Y(n173), 
	.A(co6));
   INVX1 U141 (.Y(n176), 
	.A(\a6/c1 ));
   INVX1 U142 (.Y(n179), 
	.A(\a6/c2 ));
   INVX1 U143 (.Y(n182), 
	.A(\a6/c3 ));
   INVX1 U144 (.Y(n185), 
	.A(\a6/c4 ));
   INVX1 U145 (.Y(n188), 
	.A(\a6/c5 ));
   INVX1 U146 (.Y(n191), 
	.A(\a6/c6 ));
   INVX1 U147 (.Y(\a0/a0/n1 ), 
	.A(ci));
endmodule

