/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s292_1
#  OS:                Linux x86_64(Host ID saturn.ece.iit.edu)
#  Generated on:      Sat Nov 17 15:27:27 2012
#  Design:            adder_tree
#  Command:           saveNetlist -excludeLeafCell final.v
###############################################################
*/
module adder_tree (
	s, 
	co, 
	a, 
	b, 
	c, 
	d, 
	e, 
	f, 
	g, 
	h, 
	ci);
   output [6:0] s;
   output co;
   input [6:0] a;
   input [6:0] b;
   input [6:0] c;
   input [6:0] d;
   input [6:0] e;
   input [6:0] f;
   input [6:0] g;
   input [6:0] h;
   input ci;

   // Internal wires
   wire \ts2[6] ;
   wire \a1/ts[6] ;
   wire \a1/ts[5] ;
   wire \a1/ts[4] ;
   wire \a1/ts[3] ;
   wire \a1/ts[2] ;
   wire \a1/ts[1] ;
   wire \a1/ts[0] ;
   wire \a1/tc[6] ;
   wire \a1/tc[5] ;
   wire \a1/tc[4] ;
   wire \a1/tc[3] ;
   wire \a1/tc[2] ;
   wire \a1/tc[1] ;
   wire \a4/c6 ;
   wire \a4/c5 ;
   wire \a4/c4 ;
   wire \a4/c3 ;
   wire \a1/s00/n3 ;
   wire \a1/s00/n2 ;
   wire \a1/s00/n1 ;
   wire \a3/ts[6] ;
   wire \a3/ts[5] ;
   wire \a3/ts[4] ;
   wire \a3/ts[3] ;
   wire \a3/ts[2] ;
   wire \a3/ts[1] ;
   wire \a3/tc[6] ;
   wire \a3/tc[5] ;
   wire \a3/tc[4] ;
   wire \a3/tc[3] ;
   wire \a3/tc[2] ;
   wire \a2/ts[6] ;
   wire \a2/ts[5] ;
   wire \a2/ts[4] ;
   wire \a2/ts[3] ;
   wire \a2/ts[2] ;
   wire \a2/ts[1] ;
   wire \a2/ts[0] ;
   wire \a2/tc[6] ;
   wire \a2/tc[5] ;
   wire \a2/tc[4] ;
   wire \a2/tc[3] ;
   wire \a2/tc[2] ;
   wire \a2/tc[1] ;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire [6:0] ts1;
   wire [6:0] tc1;
   wire [6:0] tc2;
   wire [6:0] ts3;
   wire [6:0] tc3;

   XNOR2X1 \a1/s00/U5  (.Y(\a1/s00/n2 ), 
	.B(b[0]), 
	.A(a[0]));
   OAI21X1 \a1/s00/U3  (.Y(\a1/tc[1] ), 
	.C(n39), 
	.B(\a1/s00/n1 ), 
	.A(\a1/s00/n2 ));
   XOR2X1 \a1/s00/U2  (.Y(\a1/ts[0] ), 
	.B(\a1/s00/n2 ), 
	.A(\a1/s00/n1 ));
   XNOR2X1 \a4/a6/U5  (.Y(n159), 
	.B(tc3[6]), 
	.A(ts3[6]));
   OAI21X1 \a4/a6/U3  (.Y(co), 
	.C(n5), 
	.B(n158), 
	.A(n159));
   XOR2X1 \a4/a6/U2  (.Y(s[6]), 
	.B(n159), 
	.A(n158));
   XNOR2X1 \a4/a5/U5  (.Y(n156), 
	.B(tc3[5]), 
	.A(ts3[5]));
   OAI21X1 \a4/a5/U3  (.Y(\a4/c6 ), 
	.C(n4), 
	.B(n155), 
	.A(n156));
   XOR2X1 \a4/a5/U2  (.Y(s[5]), 
	.B(n156), 
	.A(n155));
   XNOR2X1 \a4/a4/U5  (.Y(n153), 
	.B(tc3[4]), 
	.A(ts3[4]));
   OAI21X1 \a4/a4/U3  (.Y(\a4/c5 ), 
	.C(n27), 
	.B(n152), 
	.A(n153));
   XOR2X1 \a4/a4/U2  (.Y(s[4]), 
	.B(n153), 
	.A(n152));
   XNOR2X1 \a4/a3/U5  (.Y(n150), 
	.B(tc3[3]), 
	.A(ts3[3]));
   OAI21X1 \a4/a3/U3  (.Y(\a4/c4 ), 
	.C(n6), 
	.B(n149), 
	.A(n150));
   XOR2X1 \a4/a3/U2  (.Y(s[3]), 
	.B(n150), 
	.A(n149));
   XNOR2X1 \a4/a2/U5  (.Y(n147), 
	.B(tc3[2]), 
	.A(ts3[2]));
   OAI21X1 \a4/a2/U3  (.Y(\a4/c3 ), 
	.C(n19), 
	.B(n41), 
	.A(n147));
   XOR2X1 \a4/a2/U2  (.Y(s[2]), 
	.B(n147), 
	.A(n41));
   XOR2X1 \a4/a1/U2  (.Y(s[1]), 
	.B(n42), 
	.A(n51));
   XOR2X1 \a4/a0/U2  (.Y(s[0]), 
	.B(n2), 
	.A(n146));
   XNOR2X1 \a3/s15/U5  (.Y(n144), 
	.B(tc2[5]), 
	.A(\a3/ts[5] ));
   OAI21X1 \a3/s15/U3  (.Y(tc3[6]), 
	.C(n7), 
	.B(n143), 
	.A(n144));
   XOR2X1 \a3/s15/U2  (.Y(ts3[5]), 
	.B(n144), 
	.A(n143));
   XNOR2X1 \a3/s14/U5  (.Y(n141), 
	.B(tc2[4]), 
	.A(\a3/ts[4] ));
   OAI21X1 \a3/s14/U3  (.Y(tc3[5]), 
	.C(n8), 
	.B(n140), 
	.A(n141));
   XOR2X1 \a3/s14/U2  (.Y(ts3[4]), 
	.B(n141), 
	.A(n140));
   XNOR2X1 \a3/s13/U5  (.Y(n138), 
	.B(tc2[3]), 
	.A(\a3/ts[3] ));
   OAI21X1 \a3/s13/U3  (.Y(tc3[4]), 
	.C(n9), 
	.B(n137), 
	.A(n138));
   XOR2X1 \a3/s13/U2  (.Y(ts3[3]), 
	.B(n138), 
	.A(n137));
   XNOR2X1 \a3/s12/U5  (.Y(n135), 
	.B(tc2[2]), 
	.A(\a3/ts[2] ));
   OAI21X1 \a3/s12/U3  (.Y(tc3[3]), 
	.C(n10), 
	.B(n134), 
	.A(n135));
   XOR2X1 \a3/s12/U2  (.Y(ts3[2]), 
	.B(n135), 
	.A(n134));
   XNOR2X1 \a3/s11/U5  (.Y(n132), 
	.B(n56), 
	.A(\a3/ts[1] ));
   OAI21X1 \a3/s11/U3  (.Y(tc3[2]), 
	.C(n31), 
	.B(n50), 
	.A(n132));
   XNOR2X1 \a3/s05/U5  (.Y(n130), 
	.B(tc1[5]), 
	.A(ts1[5]));
   OAI21X1 \a3/s05/U3  (.Y(\a3/tc[6] ), 
	.C(n11), 
	.B(n49), 
	.A(n130));
   XOR2X1 \a3/s05/U2  (.Y(\a3/ts[5] ), 
	.B(n130), 
	.A(n49));
   XNOR2X1 \a3/s04/U5  (.Y(n128), 
	.B(tc1[4]), 
	.A(ts1[4]));
   OAI21X1 \a3/s04/U3  (.Y(\a3/tc[5] ), 
	.C(n12), 
	.B(n48), 
	.A(n128));
   XOR2X1 \a3/s04/U2  (.Y(\a3/ts[4] ), 
	.B(n128), 
	.A(n48));
   XNOR2X1 \a3/s03/U5  (.Y(n126), 
	.B(tc1[3]), 
	.A(ts1[3]));
   OAI21X1 \a3/s03/U3  (.Y(\a3/tc[4] ), 
	.C(n13), 
	.B(n47), 
	.A(n126));
   XOR2X1 \a3/s03/U2  (.Y(\a3/ts[3] ), 
	.B(n126), 
	.A(n47));
   XNOR2X1 \a3/s02/U5  (.Y(n124), 
	.B(tc1[2]), 
	.A(ts1[2]));
   OAI21X1 \a3/s02/U3  (.Y(\a3/tc[3] ), 
	.C(n14), 
	.B(n44), 
	.A(n124));
   XOR2X1 \a3/s02/U2  (.Y(\a3/ts[2] ), 
	.B(n124), 
	.A(n44));
   XNOR2X1 \a3/s01/U5  (.Y(n122), 
	.B(n52), 
	.A(ts1[1]));
   OAI21X1 \a3/s01/U3  (.Y(\a3/tc[2] ), 
	.C(n15), 
	.B(n43), 
	.A(n122));
   XOR2X1 \a3/s01/U2  (.Y(\a3/ts[1] ), 
	.B(n122), 
	.A(n43));
   XNOR2X1 \a2/s16/U5  (.Y(n121), 
	.B(h[6]), 
	.A(\a2/ts[6] ));
   XOR2X1 \a2/s16/U2  (.Y(\ts2[6] ), 
	.B(n121), 
	.A(n120));
   XNOR2X1 \a2/s15/U5  (.Y(n118), 
	.B(h[5]), 
	.A(\a2/ts[5] ));
   OAI21X1 \a2/s15/U3  (.Y(tc2[6]), 
	.C(n40), 
	.B(n117), 
	.A(n118));
   XNOR2X1 \a2/s14/U5  (.Y(n115), 
	.B(h[4]), 
	.A(\a2/ts[4] ));
   OAI21X1 \a2/s14/U3  (.Y(tc2[5]), 
	.C(n18), 
	.B(n114), 
	.A(n115));
   XNOR2X1 \a2/s13/U5  (.Y(n112), 
	.B(h[3]), 
	.A(\a2/ts[3] ));
   OAI21X1 \a2/s13/U3  (.Y(tc2[4]), 
	.C(n20), 
	.B(n111), 
	.A(n112));
   XNOR2X1 \a2/s12/U5  (.Y(n109), 
	.B(h[2]), 
	.A(\a2/ts[2] ));
   OAI21X1 \a2/s12/U3  (.Y(tc2[3]), 
	.C(n22), 
	.B(n108), 
	.A(n109));
   XNOR2X1 \a2/s11/U5  (.Y(n106), 
	.B(h[1]), 
	.A(\a2/ts[1] ));
   OAI21X1 \a2/s11/U3  (.Y(tc2[2]), 
	.C(n24), 
	.B(n105), 
	.A(n106));
   XNOR2X1 \a2/s05/U5  (.Y(n103), 
	.B(f[5]), 
	.A(e[5]));
   OAI21X1 \a2/s05/U3  (.Y(\a2/tc[6] ), 
	.C(n29), 
	.B(n102), 
	.A(n103));
   XOR2X1 \a2/s05/U2  (.Y(\a2/ts[5] ), 
	.B(n103), 
	.A(n102));
   XNOR2X1 \a2/s04/U5  (.Y(n100), 
	.B(f[4]), 
	.A(e[4]));
   OAI21X1 \a2/s04/U3  (.Y(\a2/tc[5] ), 
	.C(n26), 
	.B(n99), 
	.A(n100));
   XOR2X1 \a2/s04/U2  (.Y(\a2/ts[4] ), 
	.B(n100), 
	.A(n99));
   XNOR2X1 \a2/s03/U5  (.Y(n97), 
	.B(f[3]), 
	.A(e[3]));
   OAI21X1 \a2/s03/U3  (.Y(\a2/tc[4] ), 
	.C(n32), 
	.B(n96), 
	.A(n97));
   XOR2X1 \a2/s03/U2  (.Y(\a2/ts[3] ), 
	.B(n97), 
	.A(n96));
   XNOR2X1 \a2/s02/U5  (.Y(n94), 
	.B(f[2]), 
	.A(e[2]));
   OAI21X1 \a2/s02/U3  (.Y(\a2/tc[3] ), 
	.C(n34), 
	.B(n93), 
	.A(n94));
   XOR2X1 \a2/s02/U2  (.Y(\a2/ts[2] ), 
	.B(n94), 
	.A(n93));
   XNOR2X1 \a2/s01/U5  (.Y(n91), 
	.B(f[1]), 
	.A(e[1]));
   OAI21X1 \a2/s01/U3  (.Y(\a2/tc[2] ), 
	.C(n36), 
	.B(n90), 
	.A(n91));
   XOR2X1 \a2/s01/U2  (.Y(\a2/ts[1] ), 
	.B(n91), 
	.A(n90));
   XNOR2X1 \a2/s00/U5  (.Y(n88), 
	.B(f[0]), 
	.A(e[0]));
   OAI21X1 \a2/s00/U3  (.Y(\a2/tc[1] ), 
	.C(n38), 
	.B(n87), 
	.A(n88));
   XOR2X1 \a2/s00/U2  (.Y(\a2/ts[0] ), 
	.B(n88), 
	.A(n87));
   XNOR2X1 \a1/s15/U5  (.Y(n85), 
	.B(d[5]), 
	.A(\a1/ts[5] ));
   OAI21X1 \a1/s15/U3  (.Y(tc1[6]), 
	.C(n17), 
	.B(n84), 
	.A(n85));
   XOR2X1 \a1/s15/U2  (.Y(ts1[5]), 
	.B(n85), 
	.A(n84));
   XNOR2X1 \a1/s14/U5  (.Y(n82), 
	.B(d[4]), 
	.A(\a1/ts[4] ));
   OAI21X1 \a1/s14/U3  (.Y(tc1[5]), 
	.C(n16), 
	.B(n81), 
	.A(n82));
   XOR2X1 \a1/s14/U2  (.Y(ts1[4]), 
	.B(n82), 
	.A(n81));
   XNOR2X1 \a1/s13/U5  (.Y(n79), 
	.B(d[3]), 
	.A(\a1/ts[3] ));
   OAI21X1 \a1/s13/U3  (.Y(tc1[4]), 
	.C(n21), 
	.B(n78), 
	.A(n79));
   XOR2X1 \a1/s13/U2  (.Y(ts1[3]), 
	.B(n79), 
	.A(n78));
   XNOR2X1 \a1/s12/U5  (.Y(n76), 
	.B(d[2]), 
	.A(\a1/ts[2] ));
   OAI21X1 \a1/s12/U3  (.Y(tc1[3]), 
	.C(n23), 
	.B(n75), 
	.A(n76));
   XOR2X1 \a1/s12/U2  (.Y(ts1[2]), 
	.B(n76), 
	.A(n75));
   XNOR2X1 \a1/s11/U5  (.Y(n73), 
	.B(d[1]), 
	.A(\a1/ts[1] ));
   OAI21X1 \a1/s11/U3  (.Y(tc1[2]), 
	.C(n25), 
	.B(n72), 
	.A(n73));
   XOR2X1 \a1/s11/U2  (.Y(ts1[1]), 
	.B(n73), 
	.A(n72));
   XNOR2X1 \a1/s05/U5  (.Y(n70), 
	.B(b[5]), 
	.A(a[5]));
   OAI21X1 \a1/s05/U3  (.Y(\a1/tc[6] ), 
	.C(n30), 
	.B(n69), 
	.A(n70));
   XOR2X1 \a1/s05/U2  (.Y(\a1/ts[5] ), 
	.B(n70), 
	.A(n69));
   XNOR2X1 \a1/s04/U5  (.Y(n67), 
	.B(b[4]), 
	.A(a[4]));
   OAI21X1 \a1/s04/U3  (.Y(\a1/tc[5] ), 
	.C(n28), 
	.B(n66), 
	.A(n67));
   XOR2X1 \a1/s04/U2  (.Y(\a1/ts[4] ), 
	.B(n67), 
	.A(n66));
   XNOR2X1 \a1/s03/U5  (.Y(n64), 
	.B(b[3]), 
	.A(a[3]));
   OAI21X1 \a1/s03/U3  (.Y(\a1/tc[4] ), 
	.C(n33), 
	.B(n63), 
	.A(n64));
   XOR2X1 \a1/s03/U2  (.Y(\a1/ts[3] ), 
	.B(n64), 
	.A(n63));
   XNOR2X1 \a1/s02/U5  (.Y(n61), 
	.B(b[2]), 
	.A(a[2]));
   OAI21X1 \a1/s02/U3  (.Y(\a1/tc[3] ), 
	.C(n35), 
	.B(n60), 
	.A(n61));
   XOR2X1 \a1/s02/U2  (.Y(\a1/ts[2] ), 
	.B(n61), 
	.A(n60));
   XNOR2X1 \a1/s01/U5  (.Y(n58), 
	.B(b[1]), 
	.A(a[1]));
   OAI21X1 \a1/s01/U3  (.Y(\a1/tc[2] ), 
	.C(n37), 
	.B(n57), 
	.A(n58));
   XOR2X1 \a1/s01/U2  (.Y(\a1/ts[1] ), 
	.B(n58), 
	.A(n57));
   XNOR2X1 U1 (.Y(n1), 
	.B(d[0]), 
	.A(\a1/ts[0] ));
   XNOR2X1 U2 (.Y(n2), 
	.B(n1), 
	.A(n3));
   XNOR2X1 U3 (.Y(n3), 
	.B(h[0]), 
	.A(\a2/ts[0] ));
   AND2X1 U4 (.Y(n157), 
	.B(tc3[5]), 
	.A(ts3[5]));
   INVX1 U5 (.Y(n4), 
	.A(n157));
   AND2X1 U6 (.Y(n160), 
	.B(tc3[6]), 
	.A(ts3[6]));
   INVX1 U7 (.Y(n5), 
	.A(n160));
   AND2X1 U8 (.Y(n151), 
	.B(tc3[3]), 
	.A(ts3[3]));
   INVX1 U9 (.Y(n6), 
	.A(n151));
   AND2X1 U10 (.Y(n145), 
	.B(tc2[5]), 
	.A(\a3/ts[5] ));
   INVX1 U11 (.Y(n7), 
	.A(n145));
   AND2X1 U12 (.Y(n142), 
	.B(tc2[4]), 
	.A(\a3/ts[4] ));
   INVX1 U13 (.Y(n8), 
	.A(n142));
   AND2X1 U14 (.Y(n139), 
	.B(tc2[3]), 
	.A(\a3/ts[3] ));
   INVX1 U15 (.Y(n9), 
	.A(n139));
   AND2X1 U16 (.Y(n136), 
	.B(tc2[2]), 
	.A(\a3/ts[2] ));
   INVX1 U17 (.Y(n10), 
	.A(n136));
   AND2X1 U18 (.Y(n131), 
	.B(tc1[5]), 
	.A(ts1[5]));
   INVX1 U19 (.Y(n11), 
	.A(n131));
   AND2X1 U20 (.Y(n129), 
	.B(tc1[4]), 
	.A(ts1[4]));
   INVX1 U21 (.Y(n12), 
	.A(n129));
   AND2X1 U22 (.Y(n127), 
	.B(tc1[3]), 
	.A(ts1[3]));
   INVX1 U23 (.Y(n13), 
	.A(n127));
   AND2X1 U24 (.Y(n125), 
	.B(tc1[2]), 
	.A(ts1[2]));
   INVX1 U25 (.Y(n14), 
	.A(n125));
   AND2X1 U26 (.Y(n123), 
	.B(n52), 
	.A(ts1[1]));
   INVX1 U27 (.Y(n15), 
	.A(n123));
   AND2X1 U28 (.Y(n83), 
	.B(d[4]), 
	.A(\a1/ts[4] ));
   INVX1 U29 (.Y(n16), 
	.A(n83));
   AND2X1 U30 (.Y(n86), 
	.B(d[5]), 
	.A(\a1/ts[5] ));
   INVX1 U31 (.Y(n17), 
	.A(n86));
   AND2X1 U32 (.Y(n116), 
	.B(h[4]), 
	.A(\a2/ts[4] ));
   INVX1 U33 (.Y(n18), 
	.A(n116));
   AND2X1 U34 (.Y(n148), 
	.B(tc3[2]), 
	.A(ts3[2]));
   INVX1 U35 (.Y(n19), 
	.A(n148));
   AND2X1 U36 (.Y(n113), 
	.B(h[3]), 
	.A(\a2/ts[3] ));
   INVX1 U37 (.Y(n20), 
	.A(n113));
   AND2X1 U38 (.Y(n80), 
	.B(d[3]), 
	.A(\a1/ts[3] ));
   INVX1 U39 (.Y(n21), 
	.A(n80));
   AND2X1 U40 (.Y(n110), 
	.B(h[2]), 
	.A(\a2/ts[2] ));
   INVX1 U41 (.Y(n22), 
	.A(n110));
   AND2X1 U42 (.Y(n77), 
	.B(d[2]), 
	.A(\a1/ts[2] ));
   INVX1 U43 (.Y(n23), 
	.A(n77));
   AND2X1 U44 (.Y(n107), 
	.B(h[1]), 
	.A(\a2/ts[1] ));
   INVX1 U45 (.Y(n24), 
	.A(n107));
   AND2X1 U46 (.Y(n74), 
	.B(d[1]), 
	.A(\a1/ts[1] ));
   INVX1 U47 (.Y(n25), 
	.A(n74));
   AND2X1 U48 (.Y(n101), 
	.B(f[4]), 
	.A(e[4]));
   INVX1 U49 (.Y(n26), 
	.A(n101));
   AND2X1 U50 (.Y(n154), 
	.B(tc3[4]), 
	.A(ts3[4]));
   INVX1 U51 (.Y(n27), 
	.A(n154));
   AND2X1 U52 (.Y(n68), 
	.B(b[4]), 
	.A(a[4]));
   INVX1 U53 (.Y(n28), 
	.A(n68));
   AND2X1 U54 (.Y(n104), 
	.B(f[5]), 
	.A(e[5]));
   INVX1 U55 (.Y(n29), 
	.A(n104));
   AND2X1 U56 (.Y(n71), 
	.B(b[5]), 
	.A(a[5]));
   INVX1 U57 (.Y(n30), 
	.A(n71));
   AND2X1 U58 (.Y(n133), 
	.B(n56), 
	.A(\a3/ts[1] ));
   INVX1 U59 (.Y(n31), 
	.A(n133));
   AND2X1 U60 (.Y(n98), 
	.B(f[3]), 
	.A(e[3]));
   INVX1 U61 (.Y(n32), 
	.A(n98));
   AND2X1 U62 (.Y(n65), 
	.B(b[3]), 
	.A(a[3]));
   INVX1 U63 (.Y(n33), 
	.A(n65));
   AND2X1 U64 (.Y(n95), 
	.B(f[2]), 
	.A(e[2]));
   INVX1 U65 (.Y(n34), 
	.A(n95));
   AND2X1 U66 (.Y(n62), 
	.B(b[2]), 
	.A(a[2]));
   INVX1 U67 (.Y(n35), 
	.A(n62));
   AND2X1 U68 (.Y(n92), 
	.B(f[1]), 
	.A(e[1]));
   INVX1 U69 (.Y(n36), 
	.A(n92));
   AND2X1 U70 (.Y(n59), 
	.B(b[1]), 
	.A(a[1]));
   INVX1 U71 (.Y(n37), 
	.A(n59));
   AND2X1 U72 (.Y(n89), 
	.B(f[0]), 
	.A(e[0]));
   INVX1 U73 (.Y(n38), 
	.A(n89));
   AND2X1 U74 (.Y(\a1/s00/n3 ), 
	.B(b[0]), 
	.A(a[0]));
   INVX1 U75 (.Y(n39), 
	.A(\a1/s00/n3 ));
   AND2X1 U76 (.Y(n119), 
	.B(h[5]), 
	.A(\a2/ts[5] ));
   INVX1 U77 (.Y(n40), 
	.A(n119));
   OR2X1 U78 (.Y(n41), 
	.B(n51), 
	.A(n42));
   XNOR2X1 U79 (.Y(n42), 
	.B(n132), 
	.A(n50));
   INVX1 U80 (.Y(n149), 
	.A(\a4/c3 ));
   INVX1 U81 (.Y(n152), 
	.A(\a4/c4 ));
   INVX1 U82 (.Y(n155), 
	.A(\a4/c5 ));
   INVX1 U83 (.Y(n158), 
	.A(\a4/c6 ));
   XNOR2X1 U84 (.Y(n43), 
	.B(n106), 
	.A(n105));
   XNOR2X1 U85 (.Y(n44), 
	.B(n109), 
	.A(n108));
   INVX1 U86 (.Y(n134), 
	.A(\a3/tc[2] ));
   XOR2X1 U87 (.Y(ts3[6]), 
	.B(n45), 
	.A(\a3/tc[6] ));
   XOR2X1 U88 (.Y(n45), 
	.B(tc2[6]), 
	.A(\a3/ts[6] ));
   XOR2X1 U89 (.Y(\a3/ts[6] ), 
	.B(n46), 
	.A(\ts2[6] ));
   XOR2X1 U90 (.Y(n46), 
	.B(tc1[6]), 
	.A(ts1[6]));
   XNOR2X1 U91 (.Y(n47), 
	.B(n112), 
	.A(n111));
   XNOR2X1 U92 (.Y(n48), 
	.B(n115), 
	.A(n114));
   XNOR2X1 U93 (.Y(n49), 
	.B(n118), 
	.A(n117));
   INVX1 U94 (.Y(n137), 
	.A(\a3/tc[3] ));
   INVX1 U95 (.Y(n140), 
	.A(\a3/tc[4] ));
   INVX1 U96 (.Y(n143), 
	.A(\a3/tc[5] ));
   OR2X1 U97 (.Y(n50), 
	.B(n3), 
	.A(n1));
   OR2X1 U98 (.Y(n51), 
	.B(n146), 
	.A(n2));
   INVX1 U99 (.Y(n72), 
	.A(\a1/tc[1] ));
   INVX1 U100 (.Y(n75), 
	.A(\a1/tc[2] ));
   AND2X1 U101 (.Y(n52), 
	.B(d[0]), 
	.A(\a1/ts[0] ));
   INVX1 U102 (.Y(\a1/s00/n1 ), 
	.A(c[0]));
   INVX1 U103 (.Y(n57), 
	.A(c[1]));
   INVX1 U104 (.Y(n60), 
	.A(c[2]));
   XOR2X1 U105 (.Y(ts1[6]), 
	.B(n53), 
	.A(\a1/tc[6] ));
   XOR2X1 U106 (.Y(n53), 
	.B(d[6]), 
	.A(\a1/ts[6] ));
   XOR2X1 U107 (.Y(\a1/ts[6] ), 
	.B(n54), 
	.A(c[6]));
   XOR2X1 U108 (.Y(n54), 
	.B(b[6]), 
	.A(a[6]));
   XOR2X1 U109 (.Y(\a2/ts[6] ), 
	.B(n55), 
	.A(g[6]));
   XOR2X1 U110 (.Y(n55), 
	.B(f[6]), 
	.A(e[6]));
   INVX1 U111 (.Y(n105), 
	.A(\a2/tc[1] ));
   INVX1 U112 (.Y(n108), 
	.A(\a2/tc[2] ));
   INVX1 U113 (.Y(n78), 
	.A(\a1/tc[3] ));
   INVX1 U114 (.Y(n111), 
	.A(\a2/tc[3] ));
   INVX1 U115 (.Y(n81), 
	.A(\a1/tc[4] ));
   INVX1 U116 (.Y(n114), 
	.A(\a2/tc[4] ));
   INVX1 U117 (.Y(n117), 
	.A(\a2/tc[5] ));
   INVX1 U118 (.Y(n84), 
	.A(\a1/tc[5] ));
   INVX1 U119 (.Y(n120), 
	.A(\a2/tc[6] ));
   AND2X1 U120 (.Y(n56), 
	.B(h[0]), 
	.A(\a2/ts[0] ));
   INVX1 U121 (.Y(n87), 
	.A(g[0]));
   INVX1 U122 (.Y(n90), 
	.A(g[1]));
   INVX1 U123 (.Y(n93), 
	.A(g[2]));
   INVX1 U124 (.Y(n63), 
	.A(c[3]));
   INVX1 U125 (.Y(n96), 
	.A(g[3]));
   INVX1 U126 (.Y(n66), 
	.A(c[4]));
   INVX1 U127 (.Y(n99), 
	.A(g[4]));
   INVX1 U128 (.Y(n102), 
	.A(g[5]));
   INVX1 U129 (.Y(n69), 
	.A(c[5]));
   INVX1 U130 (.Y(n146), 
	.A(ci));
endmodule

